### ISSUE TITLE
Login is successful, but adding items to cart fails

### ISSUE THREAD

**Issue by hallleron** [punchout-catalogs/magento2-cookie#1]
Hey,

I noticed an issue with the module. We are now able to log in via a PunchOutSetupRequest, but we cannot add items to the cart. There is always a message saying that the session has timed out.

Therefore the punchout itself is not usable.

Is there a fix for that?

**Comment by RulerOf** [comment]
After adding this module, are the Magento site's cookies being properly set with `SameSite=None`? You can find this information in the Chrome Dev Tools on the Application tab: 
![SameSite_🍪_sandbox](https://user-images.githubusercontent.com/539074/107119237-58208580-6854-11eb-9b97-d469728ab553.png)

**Comment by hallleron** [comment]
Yes they are, however I found the mistake. The JavaScript Cookie files also needed to be modified to make the page cache form key working again.
